version: '3.5'

services:
  tests:
    container_name: tests
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
#    depends_on:
#      mysql:
#        condition: service_started
#  mysql:
#    container_name: mysql
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE: 'testing'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
